version: "3"

services:
  service:
    image: gcr.io/$PROJECT_ID/$SERVICE:$COMMIT_ID
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - $PORT:$PORT
